version: '3.4'

services:
  simplecqrs-redis-view:
    image: ${DOCKER_REGISTRY-}simplecqrsredisviews
    container_name: simplecqrs-redis-view-itest
    environment:
      - LOG_LEVEL=DEBUG
      - ConnectionStrings:RedisConnection=redis:6379,allowAdmin=false     
    ports:
      - 54106:80     
      
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6479:6379   
    volumes:
      - redis-data:/data

volumes:
  redis-data: